name: Python Test

on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", "docs", ".github"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["README.md", "docs", ".github"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tooling dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Install project dependencies
        run: poetry install --all-extras --with test,dev
        working-directory: bmsdna.sql_utils
      - name: Pyright
        run: |
          poetry run pyright .
        working-directory: bmsdna.sql_utils
      - name: Test with pytest
        run: poetry run pytest  --capture=tee-sys  tests
        working-directory: bmsdna.sql_utils
